// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0IiU-o-xHTlZRIyyyOobBpIoStdNlsoo',
    appId: '1:164415538642:web:5548ef1b3f7137f881f40b',
    messagingSenderId: '164415538642',
    projectId: 'news-app-cfb5f',
    authDomain: 'news-app-cfb5f.firebaseapp.com',
    storageBucket: 'news-app-cfb5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7rb5KCxfoxoFUPdJN5eqohIx6bRdba8',
    appId: '1:164415538642:android:bf3c82a916b6cc5181f40b',
    messagingSenderId: '164415538642',
    projectId: 'news-app-cfb5f',
    storageBucket: 'news-app-cfb5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6zmQlc3OVjPOnA7wWBi2UoKGmdXqavrM',
    appId: '1:164415538642:ios:3235e63aa21b4e7f81f40b',
    messagingSenderId: '164415538642',
    projectId: 'news-app-cfb5f',
    storageBucket: 'news-app-cfb5f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6zmQlc3OVjPOnA7wWBi2UoKGmdXqavrM',
    appId: '1:164415538642:ios:3235e63aa21b4e7f81f40b',
    messagingSenderId: '164415538642',
    projectId: 'news-app-cfb5f',
    storageBucket: 'news-app-cfb5f.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0IiU-o-xHTlZRIyyyOobBpIoStdNlsoo',
    appId: '1:164415538642:web:4e97ae8b228d1ad581f40b',
    messagingSenderId: '164415538642',
    projectId: 'news-app-cfb5f',
    authDomain: 'news-app-cfb5f.firebaseapp.com',
    storageBucket: 'news-app-cfb5f.appspot.com',
  );
}
